SIG_SMEHLA/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('', include('services.urls')),
    path('news/', include('news.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path

from news import views

app_name = 'news'
urlpatterns = [
    path('create/', views.NewsCreateView.as_view(), name='create'),
    path('', views.NewsListView.as_view(), name='list'),
    path('<int:pk>/update/', views.NewsUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.NewsDeleteView.as_view(), name='delete'),
    path('<int:pk>/detail/', views.NewsDetailView.as_view(), name='detail'),

    path('services/create/<str:type>/', views.ServiceCreate.as_view(), name='service-create'),
    path('services/<int:pk>/update/', views.ServiceUpdate.as_view(), name='service-update'),
    path('services/<int:pk>/delete/', views.ServiceDelete.as_view(), name='service-delete'),

    path('legislation/', views.LegislationList.as_view(), name='legislation'),
    path('legislation/create/', views.LegislationCreate.as_view(), name='legislation-create'),
    path('legislation/<int:pk>/update/', views.LegislationUpdate.as_view(), name='legislation-update'),
    path('legislation/<int:pk>/delete/', views.LegislationDelete.as_view(), name='legislation-delete'),

    path('history/', views.HistoryView.as_view(), name='history'),
    path('director/profile/', views.DirectorProfileView.as_view(), name='director'),
    path('organization/', views.OrganizationChartView.as_view(), name='organization'),
    path('passport/info/', views.PassportInformationView.as_view(), name='passport-info'),
    path('visa/info/', views.VisaInformationView.as_view(), name='visa-info'),
    path('authorization/info/', views.AuthorizationInformationView.as_view(), name='authorization-info'),
]

services/urls.py
from django.urls import path

from services import views

app_name = 'services'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('services/status/', views.SearchStatusServiceView.as_view(), name='status'),
    path('tools/', views.ServiceToolsView.as_view(), name='tools'),

    path('client/add/', views.ClientCreateView.as_view(), name='client_create'),
    path('client/list/<type>/', views.ClientListView.as_view(), name='client_list'),
    path('client/<int:pk>/detail/', views.ClientDetailView.as_view(), name='client_detail'),
    path('client/<int:pk>/update/', views.ClientUpdateView.as_view(), name='client_update'),
    path('client/<int:pk>/delete/', views.ClientDeleteView.as_view(), name='client_delete'),

    path('service/<type>/<int:pk>/add/', views.ServiceCreateView.as_view(), name='service_create'),
    path('service/<str:type>/<int:pk>/', views.ServiceDetailView.as_view(), name='service_detail'),
    path('service/<type>/<int:pk>/update/', views.ServiceUpdateView.as_view(), name='service_update'),
    path('service/<str:type>/<int:pk>/delete/', views.ServiceDeleteView.as_view(), name='service_delete'),

    path('service/change/<int:pk>/<str:type_request>', views.ChangeStatusServiceView.as_view(), name='change_status'),
    path('service/<int:pk>/delivery/', views.DeliveryView.as_view(), name='delivery'),
]

news/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class News(models.Model):
    def picture_news(self, filename):
        ext = filename.split('.')[-1]
        return 'news/{}/{}.{}'.format(self.pub_date, self.title, ext)

    picture = models.ImageField(_('Picture'), upload_to=picture_news)
    title = models.CharField(_('Title'), max_length=100)
    content = models.TextField(_('Content'))
    pub_date = models.DateField(_('Publication date'), auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('News')
        verbose_name_plural = _('News')


class Service(models.Model):
    def file_services(self, filename):
        ext = filename.split('.')[-1]
        return 'services/{}.{}'.format(self.service_type, ext)
    SERVICES_CHOICES = (
        ('P', 'Passport'),
        ('V', 'Visa'),
        ('R', 'Residence'),
    )

    service_type = models.CharField(_('Service'), max_length=100)
    description = models.CharField(_('Description'), max_length=250)
    file = models.FileField(_('File'), upload_to=file_services)
    service = models.CharField(verbose_name=_('Service Type'), max_length=1, choices=SERVICES_CHOICES)

    def __str__(self):
        return self.service_type

    class Meta:
        verbose_name = _('Service')
        verbose_name_plural = _('Services')


class Legislation(models.Model):
    def file_legislation(self, filename):
        ext = filename.split('.')[-1]
        return 'legislation/{}.{}'.format(self.service_type, ext)

    service_type = models.CharField(_('Legislation Type'), max_length=100)
    description = models.CharField(_('Description'), max_length=250)
    file = models.FileField(_('File'), upload_to=file_legislation)

    def __str__(self):
        return self.service_type

    class Meta:
        verbose_name = _('Legislation')
        verbose_name_plural = _('Legislation')

news/forms.py
from django import forms

from news import models


class NewsCreateForm(forms.ModelForm):
    class Meta:
        model = models.News
        fields = '__all__'
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control md-textarea'}),
        }


class ServiceUpdateForm(forms.ModelForm):
    class Meta:
        model = models.Service
        exclude = ['service']
        widgets = {
            'service_type': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.TextInput(attrs={'class': 'form-control'}),
            'file': forms.FileInput(attrs={'class': 'form-control'}),
        }


class ServiceCreateForm(forms.ModelForm):
    class Meta:
        model = models.Service
        fields = '__all__'
        widgets = {
            'service': forms.Select(attrs={'class': 'form-control'}),
            'service_type': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.TextInput(attrs={'class': 'form-control'}),
            'file': forms.FileInput(attrs={'class': 'form-control'}),
        }

news/views.py
from django.urls import reverse_lazy
from django.views import generic

from accounts import mixins as auth_mixin
from news import forms
from news.models import News, Service, Legislation


class NewsCreateView(auth_mixin.OccupationRequiredMixin, generic.CreateView):
    model = News
    occupations = ['ADMIN', 'FAC']
    form_class = forms.NewsCreateForm

    def get_success_url(self):
        return reverse_lazy('news:detail', kwargs={'pk': self.object.pk})


class NewsDetailView(generic.DetailView):
    model = News


class NewsUpdateView(auth_mixin.LoginRequiredMixin, generic.UpdateView):
    model = News
    form_class = forms.NewsCreateForm

    def get_success_url(self):
        return reverse_lazy('news:detail', kwargs={'pk': self.object.pk})


class NewsListView(generic.ListView):
    model = News


class NewsDeleteView(auth_mixin.LoginRequiredMixin, generic.DeleteView):
    model = News
    success_url = reverse_lazy('news:list')


class ServiceCreate(auth_mixin.OccupationRequiredMixin, generic.CreateView):
    model = Service
    occupations = ['ADMIN', 'FAC']
    form_class = forms.ServiceCreateForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.service = self.kwargs.get('type')
        return super().form_valid(form)

    def get_success_url(self):
        service_type = self.kwargs.get('type')
        if service_type == 'V':
            return reverse_lazy('news:visa-info')
        elif service_type == 'P':
            return reverse_lazy('news:passport-info')
        elif service_type == 'R':
            return reverse_lazy('news:authorization-info')
        else:
            return reverse_lazy('services:index')


class ServiceUpdate(auth_mixin.OccupationRequiredMixin, generic.UpdateView):
    model = Service
    occupations = ['ADMIN', 'FAC']
    form_class = forms.ServiceUpdateForm

    def get_success_url(self):
        service = self.get_object()
        print(service.service)
        if service.service == 'P':
            return reverse_lazy('news:passport-info')
        elif service.service == 'V':
            return reverse_lazy('news:visa-info')
        else:
            return reverse_lazy('news:authorization-info')


class ServiceDelete(auth_mixin.OccupationRequiredMixin, generic.DeleteView):
    model = Service
    occupations = ['ADMIN', 'FAC']

    def get_success_url(self):
        service = self.get_object()
        print(service.service)
        if service.service == 'P':
            return reverse_lazy('news:passport-info')
        elif service.service == 'V':
            return reverse_lazy('news:visa-info')
        else:
            return reverse_lazy('news:authorization-info')


class LegislationCreate(auth_mixin.OccupationRequiredMixin, generic.CreateView):
    model = Legislation
    occupations = ['ADMIN', 'FAC']
    success_url = reverse_lazy('news:legislation')
    fields = '__all__'


class LegislationList(generic.ListView):
    model = Legislation


class LegislationUpdate(auth_mixin.OccupationRequiredMixin, generic.UpdateView):
    model = Legislation
    occupations = ['ADMIN', 'FAC']
    fields = '__all__'
    success_url = reverse_lazy('news:legislation')


class LegislationDelete(auth_mixin.OccupationRequiredMixin, generic.DeleteView):
    model = Legislation
    occupations = ['ADMIN', 'FAC']
    success_url = reverse_lazy('news:legislation')


class HistoryView(generic.TemplateView):
    template_name = 'news/history.html'


class DirectorProfileView(generic.TemplateView):
    template_name = 'news/director_profile.html'


class OrganizationChartView(generic.TemplateView):
    template_name = 'news/organization.html'


class PassportInformationView(generic.ListView):
    model = Service
    template_name = 'news/passport_info.html'
    queryset = Service.objects.filter(service='P')


class VisaInformationView(generic.ListView):
    model = Service
    template_name = 'news/visa_info.html'
    queryset = Service.objects.filter(service='V')


class AuthorizationInformationView(generic.ListView):
    model = Service
    template_name = 'news/authorization_info.html'
    queryset = Service.objects.filter(service='R')

news/templates/news/authorization_info.html
{% extends 'navbar.html' %}
{% load static %}
{% load i18n %}

{% block title %}
    {% trans 'Residence Authorization Information' %}
{% endblock %}

{% block main %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <p class="text-justify">informacion relativa a autorizacion de residencia</p>
            </div>
        </div>
        {% include 'news/services_template.html' with type='R' %}
    </div>
{% endblock %}

news/templates/news/director_profile.html
{% extends 'navbar.html' %}
{% load static %}
{% load i18n %}

{% block title %}
    {% trans 'Director profile' %}
{% endblock %}

{% block main %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <h2 class="h2 text-center">Perfil do director</h2>
            </div>
            <div class="col-12">
                <p class="text-justify">José Paulino Cunha da Silva entrou em funções no final de 2012 como Director
                    Nacional do Serviço de
                    Migração e Estrangeiros.</p>
            </div>
            <div class="col-12">
                <p class="text-justify">Licenciado em Direito pela Universidade Estatal de Kiev/Ucrânia, o responsável é
                    ainda Mestre em Ciências
                    Jurídico-Internacionais pela Faculdade de Direito de Lisboa, Mestre em Administração e Gestão pela
                    Universidade de Wexford, Zurich.</p>
                <p class="text-justify">Advogado, membro da Ordem dos Advogados de Angola, é membro da Sociedade
                    Americana do Direito
                    Internacional desde 1997. A nível profissional, desempenhou as funções de professor colaborador do
                    Instituto Médio de Economia de Luanda entre 1992-1993 e foi Consultor Jurídico da Loangos
                    Associados,
                    Sematex, Imporafrica, Maboque e Moneta-Casa de Câmbios, entre 1991-1993.</p>
                <p class="text-justify"> A diplomacia internacional é um campo bem conhecido do novo líder do SME.
                    Desempenhou as funções de
                    Primeiro-Secretário da Embaixada de Angola em Portugal (1993-1997).</p>
                <p class="text-justify">Foi Conselheiro da Missão Permanente da República de Angola junto da ONU
                    (1997-2003) e nessa qualidade
                    participou em varias reuniões e conferências internacionais sobre negociações de instrumentos
                    jurídicos
                    internacionaisno domínio da diplomacia preventiva, resolução de conflitos e desarmamento e segurança
                    internacional (Noruega, Suíça, Alemanha, Holanda, Áustria, Nova lorque, Washington e Novo México),
                    tendo
                    também assistido a várias reuniões dedicadas ao Direito do Mar que decorreram na sede das Nações
                    Unidas.</p>
                <p class="text-justify">Foi conselheiro e membro da equipa angolana no Conselho de Segurança das Nações
                    Unidas (2003-2004).</p>
                <p class="text-justify">O responsável desempenhou, até há bem pouco tempo, as funções de professor
                    universitário, sendo autor dos
                    seguintes livros já publicados: “As Resoluções das Nações Unidas sobre Angola” (Junho/2002) e “A
                    Problemática do Novo Direito Internacional do Mar e os Espaços Marítimos sob jurisdição de Angola”
                    (Fevereiro/2005).</p>
                <p class="text-justify"> Mais recentemente, até aos últimos meses de 2012, ocupou o cargo de director do
                    intercâmbio e cooperação
                    do Ministério do Interior.</p>
                <p class="text-justify">Habituado a interagir num mundo multicultural, o responsável fala e escreve em
                    português, inglês,
                    espanhol e russo.</p>
            </div>
        </div>
    </div>
{% endblock %}

news/templates/news/history.html
{% extends 'navbar.html' %}
{% load static %}
{% load i18n %}

{% block title %}
    {% trans 'History' %}
{% endblock %}

{% block main %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <p class="text-justify">historia del sistema</p>
            </div>
        </div>
    </div>
{% endblock %}

news/templates/news/legislation_confirm_delete.html
{% extends 'navbar.html' %}
{% load i18n %}

{% block title %}
    {% trans 'Delete legislation' %}
{% endblock %}

{% block main %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h2 class="h2 text-center">{% trans 'Are you shure to delete this legislation?' %}</h2>
            </div>
            <div class="col-12">
                <form method="post">
                    {% csrf_token %}
                    <button class="btn btn-danger">{% trans 'Accept' %}</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

news/templates/news/legislation_form.html
{% extends 'navbar.html' %}
{% load i18n %}

{% block title %}
    {% trans 'Create legislation' %}
{% endblock %}

{% block main %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <button class="btn btn-default">Aceptar</button>
    </form>
{% endblock %}

news/templates/news/news_confirm_delete.html
{% extends 'navbar.html' %}
{% load i18n %}

{% block title %}
    {% trans 'Delete news' %}
{% endblock %}

{% block main %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h1 class="h1 text-center">
                    {% blocktrans %}Are you shure to delete the "{{ news }}" news?{% endblocktrans %}
                </h1>
            </div>

            <div class="col-12">
                <form method="post">
                    {% csrf_token %}
                    <button class="btn btn-danger">{% trans 'Accept' %}</button>
                </form>
            </div>

        </div>
    </div>
{% endblock %}

news/templates/news/news_form.html
{% extends 'navbar.html' %}
{% load static %}
{% load i18n %}

{% block title %}
    {% trans 'News' %}
{% endblock %}

{% block main %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col">
                                <div class="md-form">
                                    {{ form.title }}
                                    <label for="{{ form.title.id_for_label }}">{{ form.title.label }}</label>
                                    <span class="text-muted text-danger">{{ form.title.errors }}</span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <div class="md-form">
                                    {{ form.content }}
                                    <label for="{{ form.content.id_for_label }}">{{ form.content.label }}</label>
                                    <span class="text-muted text-danger">{{ form.content.errors }}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <img src="{% if news.picture %}{{ news.picture.url }}{% else %}{% static 'services/img/lobby.jpg' %}
                        {% endif %}" height="200">
                    {{ form.picture }}
                    <span class="text-muted text-danger">{{ form.picture.errors }}</span>
                </div>
            </div>
        </div>
        <button class="btn btn-default">{% trans 'Accept' %}</button>
    </form>
{% endblock %}

news/templates/news/news_list.html
{% extends 'navbar.html' %}
{% load i18n %}
{% load static %}

{% block title %}
    {% trans 'News' %}
{% endblock %}

{% block main %}
    <div class="container-fluid">
        {% if user.occupation == 'ADMIN' or user.occupation == 'FAC' %}
            <div class="row">
                <a href="{% url 'news:create' %}" class="btn btn-default">{% trans 'Add news' %}</a>
            </div>
        {% endif %}
        <div class="row">
            {% for news in news_list %}
                <div class="col-4">
                    <!-- Card -->
                    <div class="card" style="height: 350px;">
                        <!-- Card image -->
                        <div class="view overlay">
                            {% if news.picture %}
                                <img src="{{ news.picture.url }}" alt="Card image"
                                     class="card-img-top" height="200" width="100">
                            {% else %}
                                <img src="{% static 'accounts/img/favicon.png' %}" alt="Card image"
                                     class="card-img-top" height="200" width="100">
                            {% endif %}
                            <a href="{% url 'news:detail' news.pk %}">
                                <span class="mask rgba-white-slight"></span>
                            </a>
                        </div>

                        <!-- Card content -->
                        <div class="card-body">
                            <!-- Title -->
                            <h4 class="card-title"><a href="{% url 'news:detail' news.pk %}">{{ news.title }}</a></h4>
                            <!-- Text -->
                            <p class="card-text text-truncate">{{ news.content }}</p>
                            <!-- Button -->
                            <div class="container-fluid">
                                <div class="row">
                                    <div class="col-4">
                                        <a href="{% url 'news:detail' news.pk %}"
                                           class="btn btn-primary btn-sm">{% trans 'View news' %}</a>
                                    </div>
                                    {% if user.is_authenticated %}
                                        <div class="col-4">
                                            <a href="{% url 'news:update' news.pk %}"
                                               class="btn btn-primary btn-sm">{% trans 'Update news' %}</a>
                                        </div>
                                        <div class="col-4">
                                            <a href="{% url 'news:delete' news.pk %}"
                                               class="btn btn-danger btn-sm">{% trans 'Delete news' %}</a>
                                        </div>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

news/templates/news/organization.html
{% extends 'navbar.html' %}
{% load i18n %}

{% block title %}
    {% trans 'Organization Chart' %}
{% endblock %}

{% block main %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <p class="text-justify">organigrama</p>
            </div>
        </div>
    </div>
{% endblock %}

news/templates/news/passport_info.html
{% extends 'navbar.html' %}
{% load static %}
{% load i18n %}

{% block title %}
    {% trans 'Pasport Information' %}
{% endblock %}

{% block main %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <p class="text-justify">informacion relativa a pasaportes</p>
            </div>
        </div>
    {% include 'news/services_template.html' with type='P' %}
    </div>
{% endblock %}

news/templates/news/service_confirm_delete.html
{% extends 'navbar.html' %}
{% load i18n %}

{% block title %}
    {% trans 'Delete service' %}
{% endblock %}

{% block main %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h2 class="h2 text-center">{% trans 'Are you shure to delete this service?' %}</h2>
            </div>
            <div class="col-12">
                <form method="post">
                    {% csrf_token %}
                    <button class="btn btn-danger">{% trans 'Accept' %}</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

news/templates/news/service_form.html
{% extends 'navbar.html' %}
{% load i18n %}

{% block title %}
    {% trans 'Create service' %}
{% endblock %}

{% block main %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form }}
                    <button class="btn btn-default">{% trans 'Accept' %}</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

news/templates/news/services_template.html
{% load i18n %}

<div class="row">
    <div class="col-12 text-center">
        {% if user.occupation == 'ADMIN' or user.occupation == 'FAC' %}
            <a href="{% url 'news:service-create' type %}" class="btn btn-default">{% trans 'Add service' %}</a>
        {% endif %}
    </div>
</div>
<div class="row">
    {% for service in service_list %}
        <div class="col-12 col-md-4 my-2">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">{{ service.service_type }}</div>
                </div>
                <div class="card-body">
                    <div class="card-text">{{ service.description }}</div>
                </div>
                <div class="card-footer">
                    <a href="{{ service.file.url }}" class="btn btn-sm btn-primary"
                       download="{{ service.file }}">Descargar</a>
                    {% if user.occupation == 'ADMIN' or user.occupation == 'FAC' %}
                        <a href="{% url 'news:service-update' service.pk %}"
                           class="btn btn-sm btn-primary">{% trans 'Update' %}</a>
                        <a href="{% url 'news:service-delete' service.pk %}"
                           class="btn btn-sm btn-danger">{% trans 'Delete' %}</a>
                    {% endif %}
                </div>
            </div>
        </div>
    {% endfor %}
</div>

news/templates/news/visa_info.html
{% extends 'navbar.html' %}
{% load static %}
{% load i18n %}

{% block title %}
    {% trans 'Visa Information' %}
{% endblock %}

{% block main %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <p class="text-justify">informacion relativa a visas</p>
            </div>
        </div>
        {% include 'news/services_template.html' with type='V' %}
    </div>
{% endblock %}