SIG_SMEHLA/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('', include('services.urls')),
    path('news/', include('news.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path

from . import views

app_name = 'account'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('<int:pk>/update/', views.ProfileUpdateView.as_view(), name='profile_update'),
    path('<int:pk>/detail/', views.ProfileDetailView.as_view(), name='profile_detail'),
    # path('login/', views.LoginView.as_view(), name='login'),
]

accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('dashboard/', views.DashBoardView.as_view(), name='dashboard'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('create/', views.ProfileCreateView.as_view(), name='profile_create'),
    path('<int:pk>/update/', views.ProfileUpdateView.as_view(), name='profile_update'),
    path('<int:pk>/update/password/', views.UpdatePasswordView.as_view(), name='profile_update_password'),
    path('<int:pk>/detail/', views.ProfileDetailView.as_view(), name='profile_detail'),
    path('<int:pk>/remove/', views.ProfileDeleteView.as_view(), name='profile_delete'),

    path('reset/password/', views.PasswordResetView.as_view(), name='reset_password'),
    path('reset/password/done/', views.PasswordResetDoneView.as_view(), name='reset_password_done'),
    path('reset/password/confirm/', views.PasswordResetConfirmView.as_view(), name='reset_password_confirm'),
    path('reset/password/complete/', views.PasswordResetCompleteView.as_view(), name='reset_password_complete'),

    path('change/status/user/', views.ChangeActiveUsersView.as_view(), name='change_active_users'),
    path('send/email/', views.SendEmailView.as_view(), name='send_email'),
]

news/urls.py
from django.urls import path

from news import views

app_name = 'news'
urlpatterns = [
    path('create/', views.NewsCreateView.as_view(), name='create'),
    path('', views.NewsListView.as_view(), name='list'),
    path('<int:pk>/update/', views.NewsUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.NewsDeleteView.as_view(), name='delete'),
    path('<int:pk>/detail/', views.NewsDetailView.as_view(), name='detail'),

    path('services/create/<str:type>/', views.ServiceCreate.as_view(), name='service-create'),
    path('services/<int:pk>/update/', views.ServiceUpdate.as_view(), name='service-update'),
    path('services/<int:pk>/delete/', views.ServiceDelete.as_view(), name='service-delete'),

    path('legislation/', views.LegislationList.as_view(), name='legislation'),
    path('legislation/create/', views.LegislationCreate.as_view(), name='legislation-create'),
    path('legislation/<int:pk>/update/', views.LegislationUpdate.as_view(), name='legislation-update'),
    path('legislation/<int:pk>/delete/', views.LegislationDelete.as_view(), name='legislation-delete'),

    path('history/', views.HistoryView.as_view(), name='history'),
    path('director/profile/', views.DirectorProfileView.as_view(), name='director'),
    path('organization/', views.OrganizationChartView.as_view(), name='organization'),
    path('passport/info/', views.PassportInformationView.as_view(), name='passport-info'),
    path('visa/info/', views.VisaInformationView.as_view(), name='visa-info'),
    path('authorization/info/', views.AuthorizationInformationView.as_view(), name='authorization-info'),
]

services/urls.py
from django.urls import path

from services import views

app_name = 'services'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('services/status/', views.SearchStatusServiceView.as_view(), name='status'),
    path('tools/', views.ServiceToolsView.as_view(), name='tools'),

    path('client/add/', views.ClientCreateView.as_view(), name='client_create'),
    path('client/list/<type>/', views.ClientListView.as_view(), name='client_list'),
    path('client/<int:pk>/detail/', views.ClientDetailView.as_view(), name='client_detail'),
    path('client/<int:pk>/update/', views.ClientUpdateView.as_view(), name='client_update'),
    path('client/<int:pk>/delete/', views.ClientDeleteView.as_view(), name='client_delete'),

    path('service/<type>/<int:pk>/add/', views.ServiceCreateView.as_view(), name='service_create'),
    path('service/<str:type>/<int:pk>/', views.ServiceDetailView.as_view(), name='service_detail'),
    path('service/<type>/<int:pk>/update/', views.ServiceUpdateView.as_view(), name='service_update'),
    path('service/<str:type>/<int:pk>/delete/', views.ServiceDeleteView.as_view(), name='service_delete'),

    path('service/change/<int:pk>/<str:type_request>', views.ChangeStatusServiceView.as_view(), name='change_status'),
    path('service/<int:pk>/delivery/', views.DeliveryView.as_view(), name='delivery'),
]

account/models.py
from django.contrib.auth.models import User, AbstractUser
from django.db import models


class Profile(AbstractUser):
    born_date = models.DateField('Fecha de nacimiento', blank=True, null=True)

    class Meta:
        verbose_name = 'Perfil'
        verbose_name_plural = 'Perfiles'

    def __str__(self):
        if self.first_name and self.last_name:
            return self.get_full_name()
        else:
            return self.username

accounts/models.py
from datetime import date

from django.contrib.auth.models import User, AbstractUser, UserManager
from django.db import models
from django.utils.translation import gettext_lazy as _

from .validators import validate_born_date


class CustomUserManager(UserManager):
    def create_superuser(self, username, email, password, **extra_fields):
        extra_fields.setdefault('occupation', 'ADMIN')

        if extra_fields.get('occupation') is not 'ADMIN':
            raise ValueError('Superuser must have occupation=ADMIN.')
        return super().create_superuser(username, email, password, **extra_fields)


class Profile(AbstractUser):
    OCCUPATION_TYPE = (
        ('FAC', _('Functionary of Migratory acts')),
        ('FUF', _('Functionary of Finance')),
        ('BDAC', _('Boss of Migratory acts')),
        ('DIR', _('Director')),
        ('ADMIN', _('Administrator')),
    )
    born_date = models.DateField(_('Born date'), blank=True, null=True, validators=[validate_born_date])
    occupation = models.CharField(_('Occupation'), max_length=5, choices=OCCUPATION_TYPE, default='FAC')

    objects = CustomUserManager()

    class Meta:
        verbose_name = _('Profile')
        verbose_name_plural = _('Profiles')

    def age(self):
        if self.born_date:
            return _('%(years)d years') % {'years': date.today().year - self.born_date.year}
        else:
            return None

    def __str__(self):
        if self.first_name and self.last_name:
            return self.get_full_name()
        else:
            return self.username

account/forms.py
from django import forms

from account.models import Profile


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['first_name', 'last_name', 'email', 'born_date']
        widgets = {
            'born_date': forms.DateInput(attrs={'class': 'datepicker'})
        }

accounts/forms.py
from django import forms
from django.contrib.auth import forms as auth_forms
from django.contrib.auth import password_validation
from django.utils.translation import gettext_lazy as _
from django.core.mail import send_mail

from SIG_SMEHLA import settings
from accounts.models import Profile

from services import widgets


class LoginForm(auth_forms.AuthenticationForm):
    username = auth_forms.UsernameField(
        widget=forms.TextInput(
            attrs={'autofocus': True, 'class': 'form-control'}
        )
    )
    password = forms.CharField(
        strip=False,
        widget=forms.PasswordInput(
            attrs={'class': 'form-control'}
        )
    )


class CreateProfileForm(forms.ModelForm):
    password1 = forms.CharField(
        label=_('Password'),
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
    )
    password2 = forms.CharField(
        label=_('Repeat password'),
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )

    class Meta:
        model = Profile
        fields = ['username', 'first_name', 'last_name', 'occupation', 'born_date', 'email']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'occupation': forms.Select(attrs={'class': 'form-control'}),
            'born_date': widgets.DateInput(),
            'email': widgets.EmailInput(),
        }

    def clean_password2(self):
        # check that the two password entries match
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(_("Passwords don't match"))  # Las contraseñas no coinciden
        password_validation.validate_password(password2, self.instance)
        return password2

    def save(self, commit=True):
        # save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user


class UpdateProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['first_name', 'last_name', 'email', 'born_date', 'occupation']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'born_date': forms.DateInput(attrs={'class': 'form-control datepicker', 'type': 'date'}),
            'occupation': forms.Select(attrs={'class': 'form-control'}),
        }


class PasswordResetForm(auth_forms.PasswordResetForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))


class PasswordChangeForm(auth_forms.PasswordChangeForm):
    old_password = forms.CharField(
        label=_("Old password"),
        strip=False,
        widget=forms.PasswordInput(attrs={'autofocus': True, 'class': 'form-control'}),
    )
    new_password1 = forms.CharField(
        label=_("New password"),
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        strip=False,
        help_text=password_validation.password_validators_help_text_html(),
    )
    new_password2 = forms.CharField(
        label=_("New password confirmation"),
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
    )


class SendEmailForm(forms.Form):
    name = forms.CharField(max_length=50)
    email = forms.EmailField()
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)

    def send_email(self):
        message = _('{} <{}> send you a email: {}'.format(
            self.cleaned_data['name'],
            self.cleaned_data['email'],
            self.cleaned_data['message'],
        ))
        send_mail(
            self.cleaned_data['subject'],
            message,
            settings.ADMINS[0],
            settings.ADMINS,
            fail_silently=False,
        )

account/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.urls import reverse_lazy
from django.views import generic

from SIG_SMEHLA.settings import DASHBOARD_URL, LOGIN_URL
from account import mixins
from . import forms
from .models import Profile


class LoginView(mixins.AnonymousRequiredMixin, generic.FormView):
    form_class = AuthenticationForm
    template_name = 'account/login.html'

    def form_valid(self, form):
        login(self.request, form.get_user())
        return super(LoginView, self).form_valid(form)

    def get_success_url(self):
        return self.request.GET.get('next', reverse_lazy(DASHBOARD_URL))


class LogoutView(generic.RedirectView):
    pattern_name = LOGIN_URL
    permanent = False

    def get(self, request, *args, **kwargs):
        logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)


class DashBoardView(mixins.ProfileMixin, mixins.NavbarMixin):
    template_name = 'account/dashboard.html'


class ProfileUpdateView(generic.UpdateView, mixins.SameUserMixin):
    model = Profile
    form_class = forms.ProfileUpdateForm
    template_name = 'account/profile_update_form.html'

    def get_success_url(self):
        return reverse_lazy('account:profile_update', kwargs={'pk': self.object.pk})


class ProfileDetailView(generic.DetailView):
    model = Profile

accounts/views.py
import datetime

from django.contrib.auth import login, logout, update_session_auth_hash
from django.contrib.auth import views as auth_views
from django.db.models import Q
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse_lazy
from django.utils import timezone
from django.views import generic

from accounts import mixins
from services.models import Visa
from . import forms
from .models import Profile


class LoginView(mixins.AnonymousRequiredMixin, generic.FormView):
    form_class = forms.LoginForm
    template_name = 'accounts/login.html'

    def form_valid(self, form):
        login(self.request, form.get_user())
        return super(LoginView, self).form_valid(form)

    def get_success_url(self):
        next_url = self.request.GET.get('next', None)
        if next_url:
            return next_url
        else:
            if self.request.user.occupation == 'ADMIN':
                return reverse_lazy('accounts:dashboard')
            else:
                return reverse_lazy('services:tools')


class LogoutView(generic.RedirectView):
    pattern_name = 'services:index'
    permanent = False

    def get(self, request, *args, **kwargs):
        logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)


class DashBoardView(mixins.SuperuserRequiredMixin, mixins.NavbarMixin, generic.ListView):
    template_name = 'accounts/dashboard.html'
    tab_name = 'dashboard'
    model = Profile


class ProfileCreateView(mixins.SuperuserRequiredMixin, generic.CreateView):
    model = Profile
    form_class = forms.CreateProfileForm

    def get_success_url(self):
        return reverse_lazy('accounts:profile_detail', kwargs={'pk': self.object.pk})


class ProfileUpdateView(mixins.SameUserMixin, generic.UpdateView):
    model = Profile
    form_class = forms.UpdateProfileForm
    template_name = 'accounts/profile_update_form.html'

    def get_success_url(self):
        return reverse_lazy('accounts:profile_update', kwargs={'pk': self.object.pk})


class ProfileDetailView(mixins.LoginRequiredMixin, generic.DetailView):
    model = Profile


class ProfileDeleteView(mixins.SuperuserRequiredMixin, generic.DeleteView):
    model = Profile
    success_url = reverse_lazy('accounts:dashboard')


class UpdatePasswordView(mixins.SameUserMixin, auth_views.PasswordChangeView):
    template_name = 'accounts/password_change_form.html'
    form_class = forms.PasswordChangeForm

    def form_valid(self, form):
        form.save()
        update_session_auth_hash(self.request, form.user)
        return super(UpdatePasswordView, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('accounts:profile_detail', kwargs={'pk': self.request.user.pk})


class PasswordResetView(auth_views.PasswordResetView):
    # Send the email
    template_name = 'accounts/password_reset_form.html'
    success_url = reverse_lazy('accounts:reset_password_done')
    form_class = forms.PasswordResetForm


class PasswordResetDoneView(auth_views.PasswordResetDoneView):
    # Show a success message for the above
    template_name = 'accounts/password_reset_done.html'


class PasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    # checks the link the user clicked and prompts for a new password
    pass


class PasswordResetCompleteView(auth_views.PasswordResetCompleteView):
    # shows a success message for the above
    pass


class ChangeActiveUsersView(mixins.SuperuserRequiredMixin, generic.FormView):
    def post(self, request, *args, **kwargs):
        pk = request.POST.get('pk', None)
        if pk:
            user = Profile.objects.get(pk=pk)
            user.is_active = not user.is_active
            user.save()
            if request.is_ajax():
                return JsonResponse({'active': user.is_active, 'pk': user.pk})

        return HttpResponseRedirect('/')


class SendEmailView(generic.FormView):
    form_class = forms.SendEmailForm
    template_name = 'accounts/send_email.html'
    success_url = reverse_lazy('accounts:send_email')

    def form_valid(self, form):
        form.send_email()
        return super(SendEmailView, self).form_valid(form)

accounts/templates/accounts/dashboard.html
{% extends 'navbar.html' %}
{% load i18n %}

{% block title %}
    {% trans 'Administrate' %}
{% endblock %}

{% block main %}
    <div class="container">
        <div class="row">
            <div class="col-10"><h2 class="h2 text-center">{% trans 'Users System' %}</h2></div>
            <div class="col">
                <a href="{% url 'accounts:profile_create' %}" class="btn btn-default">{% trans 'Add user' %}</a>
            </div>
        </div>
        <div class="row">
            <table class="table table-hover table-search" cellspacing="0" width="100%" data-page-length="5">
                <thead>
                <tr>
                    <th class="th">{% trans 'Username' %}</th>
                    <th>{% trans 'Full name' %}</th>
                    <th>{% trans 'Email' %}</th>
                    <th>{% trans 'Occupation' %}</th>
                    <th>{% trans 'Is active' %}</th>
                    <th>{% trans 'Actions' %}</th>
                </tr>
                </thead>
                <tbody>
                {% for profile in profile_list %}
                    <tr>
                        <td>{{ profile.username }}</td>
                        <td>{{ profile.get_full_name }}</td>
                        <td>{{ profile.email }}</td>
                        <td>{{ profile.get_occupation_display }}</td>
                        <td>
                            <input type="checkbox" class="form-control"
                                   {% if  profile.is_active %}checked title="{% trans 'Is active' %}"
                                   {% else %}title="{% trans 'Is inactive' %}"{% endif %} data-pk="{{ profile.pk }}">
                        </td>
                        <td>
                            <a href="{% url 'accounts:profile_detail' profile.pk %}">
                                <i class="fa fa-eye"></i>
                            </a>
                            <a href="{% url 'accounts:profile_update' profile.pk %}">
                                <i class="fa fa-edit"></i>
                            </a>
                            <a href="{% url 'accounts:profile_delete' profile.pk %}">
                                <i class="fa fa-remove"></i>
                            </a>
                        </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script>
        $(function () {
            $('input[type=checkbox]').click(function () {
                let current = $(this);
                $.ajax('{% url "accounts:change_active_users" %}', {
                    method: 'POST',
                    data: {'pk': $(this).attr('data-pk')},
                    success: function (data, status) {
                        swal({
                            position: 'top-end',
                            type: status,
                            title: '{% trans "The user status has been changed" %}',
                            showConfirmButton: false,
                            timer: 1500
                        });
                        if (current.is(':checked')) {
                            current.prop("title", "{% trans 'Is active' %}");
                        } else {
                            current.prop("title", "{% trans 'Is inactive' %}");
                        }
                    },
                    error: function (data, status) {
                        swal({
                            position: 'top-end',
                            type: status,
                            title: "{% trans 'An error has been happened' %}",
                            showConfirmButton: false,
                            timer: 1500
                        });
                        console.log(data);
                    },
                });
            });
        });
    </script>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
    Entrar
{% endblock %}

{% block styles %}
    <style>
        .login {
            margin: 5% 33%;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="login">

        <div class="card">
            <!-- Material form login -->
            <h5 class="card-header info-color white-text text-center py-4">
                <strong>{% trans 'Login' %}</strong>
            </h5>

            <!-- Card content -->
            <div class="card-body px-lg-5 pt-0">
                <!-- Form -->
                <form class="text-center" style="color: #757575;" method="post">
                    {% csrf_token %}
                    <!-- Username -->
                    <div class="md-form">
                        {{ form.username }}
                        <label for="{{ form.username.id_for_label }}">{{ form.username.label }}</label>
                    </div>
                    <!-- Password -->
                    <div class="md-form">
                        {{ form.password }}
                        <label for="{{ form.password.id_for_label }}">{{ form.password.label }}</label>
                    </div>
                    <div class="d-flex justify-content-around">
                        <div>
                            <!-- Remember me -->
                            <div class="form-check">
                                <input type="checkbox" class="form-check-input" id="remember">
                                <label for="remember" class="form-check-label">{% trans 'Remember me' %}</label>
                            </div>
                        </div>
                        <div>
                            <!-- Forgot password -->
                            <a href="{% url 'accounts:reset_password' %}">{% trans 'Forgot your password?' %}</a>
                        </div>
                    </div>

                    <!-- Sign in button -->
                    <button class="btn btn-outline-info btn-rounded btn-block my-4 waves-effect z-depth-0"
                            type="submit">
                        {% trans 'Get in' %}
                    </button>
                </form>
                <!-- Form -->
            </div>
            <!-- Card content -->
        </div>
        <!-- Material form login -->
    </div>
{% endblock %}

{% block script %}
    <script>
        {% if form.non_field_errors %}
            $(function () {
                {% for error in form.non_field_errors %}
                    swal({
                        title: 'Error',
                        html: '{{ error }}',
                        type: 'error'
                    });
                {% endfor %}
            });
        {% endif %}
    </script>
{% endblock %}

accounts/templates/accounts/password_change_form.html
{% extends 'navbar.html' %}
{% load i18n %}

{% block title %}
    {% trans 'Change password' %}
{% endblock %}

{% block main %}
    <div class="container">
        <form method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col">
                    <span class="justify-content-center text-danger">
                        {{ form.non_field_errors }}
                    </span>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <div class="md-form">
                        {{ form.old_password }}
                        <label for="{{ form.old_password.id_for_label }}">{{ form.old_password.label }}</label>
                        <span class="text-muted text-danger">{{ form.old_password.errors }}</span>
                    </div>
                </div>
                <div class="col">
                    <div class="md-form">
                        {{ form.new_password1 }}
                        <label for="{{ form.new_password1.id_for_label }}">{{ form.new_password1.label }}</label>
                        <span class="text-muted text-danger">{{ form.new_password1.errors }}</span>
                        <span class="text-muted font-small">{{ form.new_password1.help_text }}</span>
                    </div>
                </div>
                <div class="col">
                    <div class="md-form">
                        {{ form.new_password2 }}
                        <label for="{{ form.new_password2.id_for_label }}">{{ form.new_password2.label }}</label>
                        <span class="text-muted text-danger">{{ form.new_password2.errors }}</span>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <button class="btn btn-default" type="submit">{% trans 'Accept' %}</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
    <h3 class="h3 my-4 text-center">
        {% trans 'Continue to be the steps that they have sent to the mail to reestablish your password.' %}
    </h3>
    <a href="{% url 'services:index' %}" class="btn btn-outline-info" style="margin: 0 45%">{% trans 'Home' %}</a>
{% endblock %}

accounts/templates/accounts/profile_detail.html
{% extends 'navbar.html' %}
{% load i18n %}

{% block title %}
    {% blocktrans %}{{ profile }}'s profile {% endblocktrans %}
{% endblock %}

{% block main %}
    <div class="container">
        <div class="row">
            <div class="col">
                <h1 class="h1 text-center">{{ profile }}</h1>
                {% if user.occupation == 'ADMIN' %}
                    {% if profile.is_active %}
                        <h5 class="green text-center">{% trans 'Is active' %}</h5>
                    {% else %}
                        <h5 class="yellow text-center">{% trans 'Is inactive' %}</h5>
                    {% endif %}
                {% endif %}
            </div>
        </div>
        <div class="row">
            <div class="col">
                <p>{% trans 'Username' %}: {{ profile.username }}</p>
            </div>
            <div class="col">
                <p>{% trans 'Born date' %}: {{ profile.born_date }}</p>
            </div>
            {% if profile.age %}
                <div class="col">
                    <p>{% trans 'Age' %}: {{ profile.age }}</p>
                </div>
            {% endif %}
        </div>
        <div class="row">
            <div class="col">
                <p>{% trans 'Occupation' %}: {{ profile.get_occupation_display }} ({{ profile.occupation }})</p>
            </div>
        </div>
    </div>
    {% if user.pk == profile.pk %}
        <a href="{% url 'accounts:profile_update_password' profile.pk %}"
           class="btn btn-default">{% trans 'Update password' %}</a>
    {% endif %}
    {% if user.pk == profile.pk or user.occupation == 'ADMIN' %}
        <a href="{% url 'accounts:profile_update' profile.pk %}" class="btn btn-default">{% trans 'Update' %}</a>
    {% endif %}
{% endblock %}

accounts/templates/accounts/profile_update_form.html
{% extends 'navbar.html' %}
{% load i18n %}

{% block title %}
    {% blocktrans %}Update {{ profile }}'s profile{% endblocktrans %}
{% endblock %}

{% block main %}
    <div class="container">
        <form method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col">
                    <div class="md-form">
                        {{ form.first_name }}
                        <label for="{{ form.first_name.id_for_label }}">{{ form.first_name.label }}</label>
                        <span class="text-muted text-danger">{{ form.first_name.errors }}</span>
                    </div>
                </div>
                <div class="col">
                    <div class="md-form">
                        {{ form.last_name }}
                        <label for="{{ form.last_name.id_for_label }}">{{ form.last_name.label }}</label>
                        <span class="text-muted text-danger">{{ form.last_name.errors }}</span>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <div class="md-form">
                        {{ form.email }}
                        <label for="{{ form.email.id_for_label }}">{{ form.email.label }}</label>
                        <span class="text-muted text-danger">{{ form.email.errors }}</span>
                    </div>
                </div>
                <div class="col">
                    <label for="{{ form.born_date.id_for_label }}">{{ form.born_date.label }}</label>
                    {{ form.born_date }}
                    <span class="text-muted text-danger">{{ form.born_date.errors }}</span>
                </div>
                {% if user.occupation == 'ADMIN' %}
                    <div class="col">
                        <label for="{{ form.occupation.id_for_label }}">{{ form.occupation.label }}</label>
                        {{ form.occupation }}
                        <span class="text-muted text-danger">{{ form.occupation.errors }}</span>
                    </div>
                {% endif %}
            </div>

            <div class="row">
                <div class="col">
                    <button class="btn btn-default" type="submit">{% trans 'Update' %}</button>
                    <a href="{% url 'accounts:profile_update_password' profile.pk %}" class="btn btn-default">
                        {% trans 'Update password' %}
                    </a>
                    {% if user.is_superuser %}
                        <a href="{% url 'accounts:profile_delete' profile.pk %}"
                           class="btn btn-danger">{% trans 'Delete' %}</a>
                    {% endif %}
                </div>
            </div>
        </form>
    </div>
{% endblock %}