SIG_SMEHLA/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('', include('services.urls')),
    path('news/', include('news.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path

from news import views

app_name = 'news'
urlpatterns = [
    path('create/', views.NewsCreateView.as_view(), name='create'),
    path('', views.NewsListView.as_view(), name='list'),
    path('<int:pk>/update/', views.NewsUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.NewsDeleteView.as_view(), name='delete'),
    path('<int:pk>/detail/', views.NewsDetailView.as_view(), name='detail'),

    path('services/create/<str:type>/', views.ServiceCreate.as_view(), name='service-create'),
    path('services/<int:pk>/update/', views.ServiceUpdate.as_view(), name='service-update'),
    path('services/<int:pk>/delete/', views.ServiceDelete.as_view(), name='service-delete'),

    path('legislation/', views.LegislationList.as_view(), name='legislation'),
    path('legislation/create/', views.LegislationCreate.as_view(), name='legislation-create'),
    path('legislation/<int:pk>/update/', views.LegislationUpdate.as_view(), name='legislation-update'),
    path('legislation/<int:pk>/delete/', views.LegislationDelete.as_view(), name='legislation-delete'),

    path('history/', views.HistoryView.as_view(), name='history'),
    path('director/profile/', views.DirectorProfileView.as_view(), name='director'),
    path('organization/', views.OrganizationChartView.as_view(), name='organization'),
    path('passport/info/', views.PassportInformationView.as_view(), name='passport-info'),
    path('visa/info/', views.VisaInformationView.as_view(), name='visa-info'),
    path('authorization/info/', views.AuthorizationInformationView.as_view(), name='authorization-info'),
]

services/urls.py
from django.urls import path

from services import views

app_name = 'services'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('services/status/', views.SearchStatusServiceView.as_view(), name='status'),
    path('tools/', views.ServiceToolsView.as_view(), name='tools'),

    path('client/add/', views.ClientCreateView.as_view(), name='client_create'),
    path('client/list/<type>/', views.ClientListView.as_view(), name='client_list'),
    path('client/<int:pk>/detail/', views.ClientDetailView.as_view(), name='client_detail'),
    path('client/<int:pk>/update/', views.ClientUpdateView.as_view(), name='client_update'),
    path('client/<int:pk>/delete/', views.ClientDeleteView.as_view(), name='client_delete'),

    path('service/<type>/<int:pk>/add/', views.ServiceCreateView.as_view(), name='service_create'),
    path('service/<str:type>/<int:pk>/', views.ServiceDetailView.as_view(), name='service_detail'),
    path('service/<type>/<int:pk>/update/', views.ServiceUpdateView.as_view(), name='service_update'),
    path('service/<str:type>/<int:pk>/delete/', views.ServiceDeleteView.as_view(), name='service_delete'),

    path('service/change/<int:pk>/<str:type_request>', views.ChangeStatusServiceView.as_view(), name='change_status'),
    path('service/<int:pk>/delivery/', views.DeliveryView.as_view(), name='delivery'),
]

services/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from accounts.models import Profile
from services import validators


class Client(models.Model):
    CIVIL_STATUS = (
        ('S', _('Single')),
        ('M', _('Married')),
        ('W', _('Widower')),
        ('D', _('Divorced')),
    )
    SEX_CHOICES = (
        ('M', _('Man')),
        ('W', _('Woman')),
    )

    def upload_file(self, filename):
        ext = filename.split('.')[-1]
        return 'clients/{}.{}'.format(self.get_full_name(), ext)

    def upload_image(self, filename):
        ext = filename.split('.')[-1]
        return 'clients/picture/{}.{}'.format(self.get_full_name(), ext)

    first_name = models.CharField(_('First name'), max_length=200)
    born_date = models.DateField(_('Born date'), validators=[validators.validate_born_date])
    civil_status = models.CharField(_('Civil status'), choices=CIVIL_STATUS, max_length=1)
    sex = models.CharField(_('Sex'), max_length=1, choices=SEX_CHOICES)
    picture = models.ImageField(_('Picture'), upload_to=upload_image, null=True, blank=True)
    father = models.CharField(_('Father name'), max_length=200, null=True, blank=True)
    mother = models.CharField(_('Mother name'), max_length=200, null=True, blank=True)
    email = models.EmailField(_('Email'), null=True, blank=True)
    phone = models.CharField(_('Phone number'), max_length=15, null=True, blank=True)
    data_attachment = models.FileField(_('Data attachment'), upload_to=upload_file, null=True, blank=True)
    # Work data
    profession = models.CharField(_('Profession'), max_length=200, null=True, blank=True)
    funcion = models.CharField(_('Function'), max_length=200, null=True, blank=True)
    work_name = models.CharField(_('Work name'), max_length=200, null=True, blank=True)
    # Work address
    province_work = models.CharField(_('Province'), max_length=50, null=True, blank=True)
    neighborhood_work = models.CharField(_('Neighborhood'), max_length=50, null=True, blank=True)
    phone_work = models.CharField(_('Phone number'), max_length=15, null=True, blank=True)
    email_work = models.EmailField(_('Email'), null=True, blank=True)
    # Current Address
    province = models.CharField(_('Province'), max_length=50, null=True, blank=True)
    municipality = models.CharField(_('Municipality'), max_length=50, null=True, blank=True)
    commune = models.CharField(_('Commune'), max_length=50, null=True, blank=True)
    neighborhood = models.CharField(_('Neighborhood'), max_length=50, null=True, blank=True)
    street = models.CharField(_('Street'), max_length=50, null=True, blank=True)
    home_no = models.CharField(_('Home No.'), max_length=10, null=True, blank=True)
    # birth address
    province_birth = models.CharField(_('Province'), max_length=50, null=True, blank=True)
    municipality_birth = models.CharField(_('Municipality'), max_length=50, null=True, blank=True)
    commune_birth = models.CharField(_('Commune'), max_length=50, null=True, blank=True)
    neighborhood_birth = models.CharField(_('Neighborhood'), max_length=50, null=True, blank=True)
    street_birth = models.CharField(_('Street'), max_length=50, null=True, blank=True)
    home_no_birth = models.CharField(_('Home No.'), max_length=10, null=True, blank=True)

    father_nationality = models.CharField(_('Father nationality'), max_length=100, null=True, blank=True)
    mother_nationality = models.CharField(_('Mother nationality'), max_length=100, null=True, blank=True)
    nationality = models.CharField(_('Origin nationality'), max_length=100)
    current_nationality = models.CharField(_('Current nationality'), max_length=100)

    def get_full_name(self):
        full_name = '%s' % self.first_name
        return full_name.strip()

    class Meta:
        verbose_name = _('Client')
        verbose_name_plural = _('Clients')

    def __str__(self):
        return self.get_full_name()


class Service(models.Model):
    SERVICE_STATUS = (
        ('1', _('Request')),
        ('2', _('Invoicing')),
        ('3', _('Revision')),
        ('4', _('Authenticating')),
        ('5', _('Deliver')),
        ('6', _('Denied')),
        ('7', _('Archive')),
    )
    SERVICE_TYPE = {
        'None': _('Unknown service type'),
        'visa': _('Visa'),
        'extension': _('Visa Extension'),
        'passport': _('Passport'),
        'residence': _('Residence authorization'),
    }
    client = models.ForeignKey(verbose_name=_('Client'), to=Client, on_delete=models.CASCADE)
    status = models.CharField(_('Status'), max_length=1, choices=SERVICE_STATUS, default='1')
    service_type = None
    process_no = models.PositiveSmallIntegerField()
    official = models.ForeignKey(Profile, on_delete=models.CASCADE, verbose_name=_('Official'), related_name='official')
    price = models.PositiveIntegerField(_('Price'), null=True, blank=True)
    # recollected status
    full_name_person = models.CharField(_('Person to delivery'), null=True, blank=True, max_length=250)
    date_to_collected = models.DateField(_('Date to collected'), blank=True, null=True)
    official_who_delivers = models.ForeignKey(Profile, on_delete=models.CASCADE,
                                              verbose_name=_('Official who delivers'), blank=True, null=True)

    def get_service_type(self):
        if self.service_type:
            return self.SERVICE_TYPE[self.service_type]
        else:
            return self.SERVICE_TYPE['None']

    def can_mod(self, user):
        if user:
            if user.occupation == 'DIR':
                return True
            elif (self.status == '1' and user.occupation == 'FAC') or (
                    self.status == '2' and user.occupation == 'FUF') or (
                    self.status == '3' and user.occupation == 'BDAC'):
                return True
        return False

    def get_previous_status(self):
        if self.status == '2':
            return self.SERVICE_STATUS[0][1]
        elif self.status == '3':
            return self.SERVICE_STATUS[1][1]
        elif self.status == '4':
            return self.SERVICE_STATUS[2][1]
        elif self.status == '5':
            return self.SERVICE_STATUS[3][1]
        else:
            return None

    def get_next_status(self):
        if self.status == '1':
            return self.SERVICE_STATUS[1][1]
        elif self.status == '2':
            return self.SERVICE_STATUS[2][1]
        elif self.status == '3':
            return self.SERVICE_STATUS[3][1]
        elif self.status == '4':
            return self.SERVICE_STATUS[4][1]
        else:
            return None

    def __str__(self):
        return '{}'.format(self.get_service_type())


class Visa(Service):
    REQUEST_TYPE_CHOICES = (
        ('SV', _('Study visa')),
        ('MTV', _('Medical Treatment visa')),
        ('TSV', _('Temporary stay visa')),
        ('STV', _('Short-term visa')),
    )

    service_type = 'visa'
    request_type = models.CharField(_('Request type'), max_length=3, choices=REQUEST_TYPE_CHOICES, blank=True,
                                    null=True)
    # passport data
    passport_no = models.CharField(_('Passport No.'), max_length=100)
    passport_issuance_place = models.CharField(_('Passport issuance place'), max_length=100)
    passport_issuance_date = models.DateField(_('Passport issuance date'))
    passport_expiration_date = models.DateField(_('Passport expiration date'))

    lodging = models.CharField(_('Lodging'), max_length=100, null=True, blank=True)  # hospedaje
    city_lodging = models.CharField(_('City lodging'), max_length=100, null=True, blank=True)
    street_lodging = models.CharField(_('Street lodging'), max_length=100, null=True, blank=True)
    no_lodging_house = models.CharField(_('Lodging house No.'), max_length=5, null=True, blank=True)
    last_entry_angola_date = models.DateField(_('Last entry angola date'))
    frontier = models.CharField(_('Frontier used'), max_length=100)
    visa_expiration_date = models.DateField(_('Visa expiration date'), null=True, blank=True)

    class Meta:
        verbose_name = _('Visa')
        verbose_name_plural = _('Visas')

    def __str__(self):
        return '{}: {} -> {}'.format(self.get_service_type(), self.client, self.get_request_type_display())


class MedicalTreatmentVisa(Visa):
    # if is a medical treatment visa
    UNITY_TYPE_CHOICES = (
        ('P', _('Public')),
        ('V', _('Private')),
    )
    unity_medical_name = models.CharField(_('Unity medical name'), max_length=100)
    unity_type = models.CharField(_('Unity type'), max_length=1, choices=UNITY_TYPE_CHOICES)
    date_init_treatment = models.DateField(_('Date init treatment'))
    data_end_treatment = models.DateField(_('Date end treatment'))


class TemporaryVisa(Visa):
    # if is a temporary visa
    REASON_CHOICES = (
        ('HR', _('Humanitarian reason')),
        ('RI', _('Mission in favor of a religious institution')),
        ('SR', _('Carrying out scientific research')),
        ('FA', _('Family Accompaniment')),
        ('VR', _('Familiar with a valid residence permit holder')),
        ('MC', _('Spouse of national citizen')),
    )
    reason = models.CharField(_('Reason'), max_length=2, choices=REASON_CHOICES)
    subsistence = models.TextField(_('Subsistence'))
    address_angola = models.TextField(_('address angola'))


class StudyVisa(Visa):
    # if is a study visa
    STUDY_PROGRAM_CHOICES = (
        ('P', _('Private')),
        ('U', _('Public')),
        ('F', _('Professional training to obtain an academic or professional degree')),
    )
    STAGES_CHOICES = (
        ('PC', _('Private companies')),
        ('UC', _('Public companies')),
    )
    study_program = models.CharField(_('Study program'), max_length=1, choices=STUDY_PROGRAM_CHOICES)
    init_date = models.DateField(_('Init date'))
    end_date = models.DateField(_('End date'))

services/templates/services/client_detail_template.html
{% load i18n %}
{% load static %}
<div class="row">
    <div class="col-lg-12 my-3">
        <h2 class="h2">{{ client.get_full_name }}</h2>
    </div>
</div>
<div class="row">
    <div class="col-lg-8">
        <div class="row">
            <div class="col-12 col-md-4">
                <p>{% trans 'Civil status' %}: {{ client.get_civil_status_display }}</p>
            </div>
            <div class="col-12 col-md-4">
                <p>{% trans 'Born date' %}: {{ client.born_date }}</p>
            </div>
            <div class="col-12 col-md-4">
                <p>{% trans 'Sex' %}: {{ client.get_sex_display }}</p>
            </div>
            <div class="col-12 col-md-6">
                <p>{% trans 'Origin nationality' %}: {{ client.nationality }}</p>
            </div>
            <div class="col-12 col-md-6">
                <p>{% trans 'Current nationality' %}: {{ client.current_nationality }}</p>
            </div>
            <div class="col-lg-6">
                <p>{% trans 'Personal Email' %}: <a href="mailto:{{ client.email }}">{{ client.email }}</a></p>
            </div>
            <div class="col-lg-6">
                <p>{% trans 'Personal Phone' %}: {{ client.phone }}</p>
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <img src="

                {% if client.picture %}{{ client.picture.url }}{% else %}{% static 'accounts/img/user.png' %}{% endif %}"
             alt="{{ client.first_name }}" width="150em" height="150em" class="img-thumbnail">
    </div>
</div>
<div class="row">
    <div class="col-12">
        <h4 class="h4 text-center">{% trans 'Parents' %}</h4>
    </div>
    <div class="col-12 col-md-6">
        <p>{% trans "Father's name" %}: {{ client.father }}</p>
    </div>
    <div class="col-12 col-md-6">
        <p>{% trans "Father's nationality" %}: {{ client.father_nationality }}</p>
    </div>
    <div class="col-12 col-md-6">
        <p>{% trans "Mother's name" %}: {{ client.mother }}</p>
    </div>
    <div class="col-12 col-md-6">
        <p>{% trans "Mother's nationality" %}: {{ client.mother_nationality }}</p>
    </div>
    <div class="col-12">
        <h4 class="h4 text-center">{% trans "Client's birth address" %}</h4>
    </div>
    <div class="col-12 col-md-6">
        {% trans 'Province' %}: {{ client.province_birth }}
    </div>
    <div class="col-12 col-md-6">
        {% trans 'Municipality' %}: {{ client.municipality_birth }}
    </div>
    <div class="col-12 col-md-6">
        {% trans 'Commune' %}: {{ client.commune_birth }}
    </div>
    <div class="col-12 col-md-6">
        {% trans 'Neighborhood' %}: {{ client.neighborhood_birth }}
    </div>
    <div class="col-12 col-md-6">
        {% trans 'Street' %}: {{ client.street_birth }}
    </div>
    <div class="col-12 col-md-6">
        {% trans 'Home No.' %}: {{ client.home_no_birth }}
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <h3 class="h3 text-center">{% trans 'Address' %}</h3>
    </div>
    <div class="col-12 col-md-6">
        {% trans 'Province' %}: {{ client.province }}
    </div>
    <div class="col-12 col-md-6">
        {% trans 'Municipality' %}: {{ client.municipality }}
    </div>
    <div class="col-12 col-md-6">
        {% trans 'Commune' %}: {{ client.commune }}
    </div>
    <div class="col-12 col-md-6">
        {% trans 'Neighborhood' %}: {{ client.neighborhood }}
    </div>
    <div class="col-12 col-md-6">
        {% trans 'Street' %}: {{ client.street }}
    </div>
    <div class="col-12 col-md-6">
        {% trans 'Home No.' %}: {{ client.home_no }}
    </div>
</div>
<div class="row">
    <div class="col-12">
        <h3 class="h3 text-center">{% trans 'Work data' %}</h3>
    </div>
    <div class="col-12 col-md-4">
        {% trans 'Profession' %}: {{ client.profession }}
    </div>
    <div class="col-12 col-md-4">
        {% trans 'Function' %}: {{ client.funcion }}
    </div>
    <div class="col-12 col-md-4">
        {% trans 'Work name' %}: {{ client.work_name }}
    </div>
    <div class="col-12 col-md-4">
        {% trans 'Province' %}: {{ client.province_work }}
    </div>
    <div class="col-12 col-md-4">
        {% trans 'Neighborhood' %}: {{ client.neighborhood_work }}
    </div>
    <div class="col-12 col-md-4">
        {% trans 'Phone work' %}: {{ client.phone_work }}
    </div>
    <div class="col-12 col-md-4">
        {% trans 'Email work' %}: {{ client.email_work }}
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        {% if client.data_attachment %}
            <p>{% trans 'Data attachment' %}:
                <a href="{{ client.data_attachment.url }}"
                   download="{{ client.get_full_name }}_{{ client.data_attachment.name }}"
                   class="btn btn-default btn-sm">
                    {% trans 'Download data attachment' %}
                </a>
            </p>
        {% endif %}
    </div>
</div>

services/templates/services/client_list.html
{% extends 'navbar.html' %}
{% load i18n %}
{% load static %}

{% block styles %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'services/css/styles.css' %}">
{% endblock %}

{% block title %}
    {% trans 'Clients list' %}
{% endblock %}

{% block main %}
    {% if client_list %}
        <table class="table table-bordered table-hover mouse-pointer table-search" cellspacing="0" width="100%">
            <thead>
            <tr>
                <th class="th-sm">{% trans 'Full name' %}</th>
                <th class="th-sm">{% trans 'Identity card' %}</th>
                <th class="th-sm">{% trans 'Born date' %}</th>
                <th class="th-sm">{% trans 'Email' %}</th>
            </tr>
            </thead>
            <tbody>
            {% for client in client_list %}
                <tr>
                    <td>
                        <a href="{% url 'services:service_create' service_type client.pk %}">
                            {{ client.get_full_name }}
                        </a>
                        <i class="fa fa-eye float-lg-right" data-toggle="modal"
                           data-target="#client-{{ forloop.counter }}"></i>
                        <!-- Client detail modal -->
                        <div class="modal fade" id="client-{{ forloop.counter }}" tabindex="-1" role="dialog"
                             aria-labelledby="client-{{ forloop.counter }}"
                             aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header text-center">
                                        <h4 class="modal-title w-100 font-weight-bold">{% trans 'Client detail' %}</h4>
                                        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <!-- Modal body-->
                                    <div class="modal-body mx-3">
                                        <div class="container-fluid">
                                            {% include 'services/client_detail_template.html' with client=client %}
                                        </div>
                                    </div>
                                    <!-- Modal body-->
                                </div>
                            </div>
                        </div>
                        <!-- Client detail modal -->
                    </td>
                    <td>{{ client.ci }}</td>
                    <td>{{ client.born_date }}</td>
                    <td>{{ client.email }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="container">
            <div class="row">
                <div class="col text-center">
                    <h3 class="text-muted">{% trans 'No client found in the system.' %}</h3>
                    <a href="{% url 'services:client_create' %}" class="btn btn-outline-default">
                        {% trans 'Create new client' %}
                    </a>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

services/templates/services/medicaltreatmentvisa_detail.html
{% extends 'navbar.html' %}
{% load i18n %}

{% block title %}
    Visa {{ medicaltreatmentvisa.client }}
{% endblock %}

{% block main %}
    <div class="container-fluid">
        {% include 'services/visa_detail_template.html' with visa=medicaltreatmentvisa only %}
        <div class="row">
            <div class="col-12">
                <h3 class="h3 text-center">{% trans 'Medical treatment visa data' %}</h3>
            </div>
            <div class="col-12">
                {% trans 'Unity medical name' %}: {{ medicaltreatmentvisa.unity_medical_name }}
            </div>
            <div class="col-12">
                {% trans 'Unity medical type' %}: {{ medicaltreatmentvisa.get_unity_type_display }}
            </div>
            <div class="col-12 col-md-6">
                {% trans 'Date init treatment' %}: {{ medicaltreatmentvisa.date_init_treatment }}
            </div>
            <div class="col-12 col-md-6">
                {% trans 'Date end treatment' %}: {{ medicaltreatmentvisa.data_end_treatment }}
            </div>
        </div>
        {% include 'services/visa_edit_template.html' with visa=medicaltreatmentvisa %}
    </div>
{% endblock %}

services/templates/services/residentvisa_detail.html
{% extends 'navbar.html' %}
{% load i18n %}

{% block title %}
    Visa {{ residentvisa.client }}
{% endblock %}

{% block main %}
    <div class="container-fluid">
        {% include 'services/visa_detail_template.html' with visa=residentvisa only %}
        <div class="row">
            <div class="col-12">
                <h3 class="h3 text-center">{% trans 'Resident visa data' %}</h3>
            </div>
            <div class="col-12 col-md-6">
                {% trans 'Reason' %}: {{ residentvisa.reason }}
            </div>
            <div class="col-12 col-md-6">
                {% trans 'Type resident' %}: {{ residentvisa.get_type_residence_display }}
            </div>
            <div class="col-12 col-md-6">
                {% trans 'Intends to reside with your household' %}: {{ residentvisa.get_live_familiar_display }}
            </div>
            <div class="col-12 col-md-6">
                {% trans 'Familiar' %}: {{ residentvisa.familiars }}
            </div>
            <div class="col-12 col-md-6">
                {% trans 'Subsistence' %}: {{ residentvisa.subsistence }}
            </div>
            <div class="col-12 col-md-6">
                {% trans 'Address in Angola' %}: {{ residentvisa.address_angola }}
            </div>

            <div class="col-12 col-md-6">
                {% trans 'Official' %}: {{ residentvisa.official }}
            </div>
        </div>
        {% include 'services/visa_edit_template.html' with visa=residentvisa %}
    </div>
{% endblock %}

services/templates/services/status_service.html
{% extends 'navbar.html' %}
{% load i18n %}

{% block title %}
    {% trans 'Service status' %}
{% endblock %}

{% block main %}
    <div class="hidden">{{ form }}</div>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="card text-center">
                    <div class="card-header">
                        {% trans 'Select the service' %}
                    </div>
                    <form method="post" action="{% url 'services:status' %}" id="search-form">
                        {% csrf_token %}
                        <div>
                            <input type="radio" id="passport" name="{{ form.request_type.name }}">
                            <label for="passport">{% trans 'Passport' %}</label>
                            <input type="radio" id="visa" name="{{ form.request_type.name }}">
                            <label for="visa">{% trans 'Visa' %}</label>
                            <input type="radio" id="residence" name="{{ form.request_type.name }}">
                            <label for="residence">{% trans 'Residence' %}</label>
                        </div>
                        <div class="card-body">
                            <div class="md-form">
                                <label for="search">{% trans 'Search' %}</label>
                                <input type="text" class="form-control" id="search"
                                       name="{{ form.search.name }}"
                                       {% if value %}value="{{ value }}"{% endif %} required>
                            </div>
                            <button type="submit" class="btn btn-default">{% trans 'Accept' %}</button>
                            <div id="loader" class="mt-3"></div>
                            <div class="hidden" id="results"></div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    {{ block.super }}
    <script>
        $(function () {
            const request_type = $('#{{ form.request_type.id_for_label }}');
            $('#passport').click(function () {
                $("label[for='search']").html('{% trans "Identity card or Personal card" %}');
                request_type.val('passport');
            });
            $('#visa').click(function () {
                $("label[for='search']").html('{% trans "Passport No." %}');
                request_type.val('visa');
            });
            $('#residence').click(function () {
                $("label[for='search']").html('{% trans "Passport No." %}');
                request_type.val('residence');
            });

            $('#search-form').submit(function (event) {
                event.preventDefault();
                const results = $('#results');
                results.addClass('hidden');
                $('#loader').html('<i class="fa fa-spinner fa-4x fa-pulse"></i>');
                $.ajax($(this).prop('action'), {
                    method: 'POST',
                    data: {
                        'request_type': $('#{{ form.request_type.id_for_label }}').val(),
                        'search': $('#search').val(),
                    },
                    success: function (response) {
                        console.log(response);
                        $('#loader').html('');
                        results.removeClass('hidden');
                        let html = '';
                        if (response['message']) {
                            html = '<h5 class="h5 text-center text-danger">' + response['message'] + '</h5>';
                        }
                        results.html(html);
                    },
                    error: function (response, status) {
                        swal({
                            title: '{% trans "Error processing request" %}',
                            type: status,
                            html: '{% trans "Could not connect to server" %}'
                        });
                    },
                });
            });
        });
    </script>
{% endblock %}

services/templates/services/studyvisa_form.html
{% extends 'navbar.html' %}
{% load i18n %}

{% block title %}
    {% trans 'Add visa' %}
{% endblock %}

{% block main %}
    <div class="container-fluid">
        <form method="post">
            {% csrf_token %}
            {% include 'services/visa_form_template.html' %}
            <div class="row">
                <div class="col-12 col-md-6">
                    <label for="{{ form.study_program.id_for_label }}">{{ form.study_program.label }}</label>
                    {{ form.study_program }}
                </div>
                <div class="col-12 col-md-6">
                    <label for="{{ form.stages_in.id_for_label }}">{{ form.stages_in.label }}</label>
                    {{ form.stages_in }}
                </div>
                <div class="col-12 col-md-6">
                    <label for="{{ form.init_date.id_for_label }}">{{ form.init_date.label }}</label>
                    {{ form.init_date }}
                </div>
                <div class="col-12 col-md-6">
                    <label for="{{ form.end_date.id_for_label }}">{{ form.end_date.label }}</label>
                    {{ form.end_date }}
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <button class="btn btn-default">{% trans 'Accept' %}</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

services/templates/services/visa_detail.html
{% extends 'navbar.html' %}
{% load i18n %}
{% load static %}
{% load service_tags %}

{% block title %}
    Visa {{ visa.client }}
{% endblock %}

{% block main %}
    <div class="container-fluid">
        {% include 'services/visa_detail_template.html' with visa=visa only %}
        {% user_can_mod_service visa user as can_mod %}
        {% if can_mod %}
            <div class="row">
                <div class="col">
                    <a href="{% url 'services:service_update' type visa.pk %}"
                       class="btn btn-default">{% trans 'Update' %}</a>
                    <a href="{% url 'services:service_delete' type visa.pk %}"
                       class="btn btn-danger">{% trans 'Delete' %}</a>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}